# roles/docker/tasks/main.yml
---
- name: Install required packages on Amazon Linux
  ansible.builtin.yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  when: ansible_facts['os_family'] == "RedHat" or ansible_facts['distribution'] == "Amazon"

- name: Add Docker repository on Amazon Linux
  ansible.builtin.yum_repository:
    name: docker
    description: Docker Repository
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat" or ansible_facts['distribution'] == "Amazon"

- name: Install Docker on Amazon Linux
  ansible.builtin.yum:
    name: docker
    state: present
  when: ansible_facts['os_family'] == "RedHat" or ansible_facts['distribution'] == "Amazon"

- name: Start Docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true

- name: Ajouter l'utilisateur ec2-user au groupe Docker
  ansible.builtin.command: sudo usermod -aG docker ec2-user