# inventaire des machines
all:
  hosts:
    ec2-instance:
      ansible_host: "{{ lookup('env', 'EC2_PUBLIC_IP') }}"
      #ansible_host: 3.80.108.100
      ansible_user: ec2-user
      #ansible_user: ubuntu
      ansible_ssh_private_key_file: private_key.pem
      #ansible_ssh_private_key_file: "./terraform/key/new-key-control.pem"