name: EC2 Instance Deploy and Model Execution

on:
  push:
    branches:
      - ingeneurie

jobs:
  terraform:
    name: Deploy EC2 instance using Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init -input=false
      working-directory: terraform/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Terraform Plan
      run: terraform plan
      working-directory: terraform/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Terraform Apply and Save EC2 IP to Secret
      id: apply
      run: |
        terraform apply -auto-approve
        # Capture uniquement l'IP publique de l'EC2
        IP=$(terraform output -raw ec2_public_ip | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
        echo "IP récupérée : $IP"
        
        # Vérifier que l'IP n'est pas vide
        if [[ -z "$IP" ]]; then
          echo "Erreur : IP non récupérée"
          exit 1
        fi

        # Mettre à jour un secret GitHub avec l'IP publique (pré-créé)
        gh secret set EC2_PUBLIC_IP --body "$IP"
      working-directory: terraform/
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_deploy:
    name: Build and Deploy Docker container
    needs: terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Create ECR repository if it doesn't exist
      run: |
        aws ecr describe-repositories --repository-names my-deep-learning-model || \
        aws ecr create-repository --repository-name my-deep-learning-model
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Build Docker image
      run: |
        docker build -t my-deep-learning-model:latest -f docker/Dockerfile .

    - name: Tag Docker image
      run: |
        docker tag my-deep-learning-model:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-deep-learning-model:latest

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-deep-learning-model:latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: SSH into EC2 and pull Docker image
      run: |
        # Créer un fichier temporaire pour la clé privée
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        # Récupérer l'IP à partir du secret GitHub
        IP="${{ secrets.EC2_PUBLIC_IP }}"
        echo "EC2 IP récupérée : $IP"
        # Ajouter l'hôte à known_hosts pour éviter le prompt SSH
        ssh-keyscan -H $IP >> ~/.ssh/known_hosts
        # Exécuter la commande SSH en utilisant l'IP publique récupérée
        ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$IP \
        "docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-deep-learning-model:latest && docker run -d -p 80:80 my-deep-learning-model"
        # Supprimer la clé privée après utilisation
        rm private_key.pem
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  follow_logs:
    name: Follow Model Execution Logs
    needs: build_and_deploy
    runs-on: ubuntu-latest

    steps:
    - name: SSH into EC2 and follow logs
      run: |
        # Créer un fichier temporaire pour la clé privée
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        # Récupérer l'IP à partir du secret GitHub
        IP="${{ secrets.EC2_PUBLIC_IP }}"
        # Suivre les logs de Docker sur l'instance EC2
        ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$IP "docker logs -f $(docker ps -q --filter ancestor=my-deep-learning-model:latest)"
        # Supprimer la clé privée après utilisation
        rm private_key.pem
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
